### ISSUE TITLE
Graph reduce

### ISSUE THREAD

**Issue by Pogozhelskaya** [JetBrains-Research/CFPQ_Data#53]
It would be cool to have an opportunity to get the graph with only edges or vertices of interest. For example, Enzyme only with broaderTransitive relationship edges.

**Comment by vdshk** [comment]
Hi, @Pogozhelskaya!

I think [it](https://jetbrains-research.github.io/CFPQ_Data/reference/graphs/generated/cfpq_data.graphs.utils.filter_edges.html#cfpq_data.graphs.utils.filter_edges) would be helpful.

Cheers,
Vadim
